export const POMODORO_VALUE = 'POMODORO_VALUE';
export const POMODORO_SECONDS = 'POMODORO_SECONDS';
export const SHORTBREAK_VALUE = 'SHORTBREAK_VALUE';
export const SHORTBREAK_SECONDS = 'SHORTBREAK_SECONDS';
export const LONGBREAK_VALUE = 'LONGBREAK_VALUE';
export const LONGBREAK_SECONDS = 'LONGBREAK_SECONDS';
